"""Add clients, invoices, and invoice_items tables

Revision ID: 2fc72e4f4005
Revises: 771e646f5ed9
Create Date: 2025-11-08 00:44:55.813762

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2fc72e4f4005'
down_revision: Union[str, Sequence[str], None] = '771e646f5ed9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clients',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('tax_id', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_clients_is_active', 'clients', ['is_active'], unique=False)
    op.create_index('idx_clients_user_id', 'clients', ['user_id'], unique=False)
    op.create_table('invoices',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('invoice_number', sa.String(length=50), nullable=False),
    sa.Column('issue_date', sa.Date(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('subtotal', sa.DECIMAL(precision=15, scale=2), nullable=False),
    sa.Column('tax_rate', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('tax_amount', sa.DECIMAL(precision=15, scale=2), nullable=True),
    sa.Column('discount_amount', sa.DECIMAL(precision=15, scale=2), nullable=True),
    sa.Column('total', sa.DECIMAL(precision=15, scale=2), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('payment_date', sa.Date(), nullable=True),
    sa.Column('payment_method', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('terms', sa.Text(), nullable=True),
    sa.Column('pdf_url', sa.Text(), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('reminder_sent_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("status IN ('draft', 'sent', 'paid', 'overdue', 'cancelled')", name='invoices_status_check'),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('invoice_number')
    )
    op.create_index('idx_invoices_client_id', 'invoices', ['client_id'], unique=False)
    op.create_index('idx_invoices_due_date', 'invoices', ['due_date'], unique=False)
    op.create_index('idx_invoices_invoice_number', 'invoices', ['invoice_number'], unique=False)
    op.create_index('idx_invoices_status', 'invoices', ['status'], unique=False)
    op.create_index('idx_invoices_user_id', 'invoices', ['user_id'], unique=False)
    op.create_table('invoice_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('invoice_id', sa.UUID(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('quantity', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('rate', sa.DECIMAL(precision=15, scale=2), nullable=False),
    sa.Column('amount', sa.DECIMAL(precision=15, scale=2), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_invoice_items_invoice_id', 'invoice_items', ['invoice_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_invoice_items_invoice_id', table_name='invoice_items')
    op.drop_table('invoice_items')
    op.drop_index('idx_invoices_user_id', table_name='invoices')
    op.drop_index('idx_invoices_status', table_name='invoices')
    op.drop_index('idx_invoices_invoice_number', table_name='invoices')
    op.drop_index('idx_invoices_due_date', table_name='invoices')
    op.drop_index('idx_invoices_client_id', table_name='invoices')
    op.drop_table('invoices')
    op.drop_index('idx_clients_user_id', table_name='clients')
    op.drop_index('idx_clients_is_active', table_name='clients')
    op.drop_table('clients')
    # ### end Alembic commands ###
