"""add_api_usage_tracking_table

Revision ID: 40280788f174
Revises: c6a09c47b60c
Create Date: 2025-12-18 17:39:06.434828

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '40280788f174'
down_revision: Union[str, Sequence[str], None] = 'c6a09c47b60c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_usage',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('service', sa.Enum('gemini', name='apiservicetype'), nullable=False, comment='API service used (e.g., Gemini)'),
    sa.Column('operation', sa.Enum('document_processing', 'text_generation', 'token_counting', name='apioperationtype'), nullable=False, comment='Type of operation performed'),
    sa.Column('model_name', sa.String(length=100), nullable=False, comment='Model used (e.g., gemini-2.5-flash)'),
    sa.Column('user_id', sa.UUID(), nullable=True, comment='User who made the request (NULL for system requests)'),
    sa.Column('input_tokens', sa.Integer(), nullable=False, comment='Number of tokens in the input (prompt + data)'),
    sa.Column('output_tokens', sa.Integer(), nullable=False, comment='Number of tokens in the output'),
    sa.Column('total_tokens', sa.Integer(), nullable=False, comment='Total tokens used (input + output)'),
    sa.Column('request_id', sa.String(length=100), nullable=True, comment='API request ID from provider (if available)'),
    sa.Column('status_code', sa.Integer(), nullable=False, comment='HTTP status code from API response'),
    sa.Column('success', sa.Integer(), nullable=False, comment='Whether the request succeeded (1) or failed (0)'),
    sa.Column('error_message', sa.Text(), nullable=True, comment='Error message if request failed'),
    sa.Column('duration_ms', sa.Integer(), nullable=True, comment='Request duration in milliseconds'),
    sa.Column('document_id', sa.UUID(), nullable=True, comment='Related document if this was document processing'),
    sa.Column('additional_data', sa.Text(), nullable=True, comment='Additional metadata as JSON string'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='When the API request was made'),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_usage_created_at'), 'api_usage', ['created_at'], unique=False)
    op.create_index(op.f('ix_api_usage_document_id'), 'api_usage', ['document_id'], unique=False)
    op.create_index(op.f('ix_api_usage_model_name'), 'api_usage', ['model_name'], unique=False)
    op.create_index(op.f('ix_api_usage_operation'), 'api_usage', ['operation'], unique=False)
    op.create_index(op.f('ix_api_usage_service'), 'api_usage', ['service'], unique=False)
    op.create_index(op.f('ix_api_usage_user_id'), 'api_usage', ['user_id'], unique=False)
    op.alter_column('bank_accounts', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('bank_accounts', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_bank_accounts_id'), 'bank_accounts', ['id'], unique=True)
    op.alter_column('documents', 'bank_account_id',
               existing_type=sa.UUID(),
               comment='Bank account this document belongs to (for bank statements)',
               existing_nullable=True)
    op.drop_index(op.f('ix_documents_id'), table_name='documents')
    op.create_index(op.f('ix_documents_id'), 'documents', ['id'], unique=True)
    op.create_index(op.f('ix_documents_document_type'), 'documents', ['document_type'], unique=False)
    op.create_index(op.f('ix_documents_status'), 'documents', ['status'], unique=False)
    op.create_index(op.f('ix_documents_user_id'), 'documents', ['user_id'], unique=False)
    op.drop_index(op.f('ix_system_banners_id'), table_name='system_banners')
    op.create_index(op.f('ix_system_banners_id'), 'system_banners', ['id'], unique=True)
    op.alter_column('transactions', 'bank_account_id',
               existing_type=sa.UUID(),
               comment='Bank account this transaction belongs to',
               existing_nullable=True)
    op.drop_index(op.f('ix_transactions_id'), table_name='transactions')
    op.create_index(op.f('ix_transactions_id'), 'transactions', ['id'], unique=True)
    op.create_index(op.f('ix_transactions_category'), 'transactions', ['category'], unique=False)
    op.create_index(op.f('ix_transactions_document_id'), 'transactions', ['document_id'], unique=False)
    op.create_index(op.f('ix_transactions_linked_invoice_id'), 'transactions', ['linked_invoice_id'], unique=False)
    op.create_index(op.f('ix_transactions_transaction_date'), 'transactions', ['transaction_date'], unique=False)
    op.create_index(op.f('ix_transactions_user_id'), 'transactions', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transactions_user_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_transaction_date'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_linked_invoice_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_document_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_category'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_id'), table_name='transactions')
    op.create_index(op.f('ix_transactions_id'), 'transactions', ['id'], unique=False)
    op.alter_column('transactions', 'bank_account_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Bank account this transaction belongs to',
               existing_nullable=True)
    op.drop_index(op.f('ix_system_banners_id'), table_name='system_banners')
    op.create_index(op.f('ix_system_banners_id'), 'system_banners', ['id'], unique=False)
    op.drop_index(op.f('ix_documents_user_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_status'), table_name='documents')
    op.drop_index(op.f('ix_documents_document_type'), table_name='documents')
    op.drop_index(op.f('ix_documents_id'), table_name='documents')
    op.create_index(op.f('ix_documents_id'), 'documents', ['id'], unique=False)
    op.alter_column('documents', 'bank_account_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Bank account this document belongs to (for bank statements)',
               existing_nullable=True)
    op.drop_index(op.f('ix_bank_accounts_id'), table_name='bank_accounts')
    op.alter_column('bank_accounts', 'updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('bank_accounts', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_api_usage_user_id'), table_name='api_usage')
    op.drop_index(op.f('ix_api_usage_service'), table_name='api_usage')
    op.drop_index(op.f('ix_api_usage_operation'), table_name='api_usage')
    op.drop_index(op.f('ix_api_usage_model_name'), table_name='api_usage')
    op.drop_index(op.f('ix_api_usage_document_id'), table_name='api_usage')
    op.drop_index(op.f('ix_api_usage_created_at'), table_name='api_usage')
    op.drop_table('api_usage')
    # ### end Alembic commands ###
