"""add_email_notification_to_documents

Revision ID: 79006ca2b241
Revises: 40280788f174
Create Date: 2025-12-18 22:56:19.152280

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '79006ca2b241'
down_revision: Union[str, Sequence[str], None] = '40280788f174'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Add column with default value to handle existing rows
    op.add_column('documents', sa.Column('email_notification_requested', sa.Boolean(), nullable=False, server_default=sa.text('false'), comment='Whether user requested email notification on completion'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'email_notification_requested')
    # ### end Alembic commands ###
