"""change_document_fk_to_set_null_and_add_source_name

Revision ID: da80d99e5273
Revises: 79006ca2b241
Create Date: 2025-12-19 20:02:33.852976

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'da80d99e5273'
down_revision: Union[str, Sequence[str], None] = '79006ca2b241'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('source_document_name', sa.String(length=255), nullable=True, comment='Original filename of the document this was imported from (preserved even after document deletion)'))
    op.alter_column('transactions', 'document_id',
               existing_type=sa.UUID(),
               comment='Document this transaction was extracted from (null for manual entries or dismissed documents)',
               existing_comment='Document this transaction was extracted from (null for manual entries)',
               existing_nullable=True)
    op.drop_constraint(op.f('transactions_document_id_fkey'), 'transactions', type_='foreignkey')
    op.create_foreign_key(None, 'transactions', 'documents', ['document_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.create_foreign_key(op.f('transactions_document_id_fkey'), 'transactions', 'documents', ['document_id'], ['id'], ondelete='CASCADE')
    op.alter_column('transactions', 'document_id',
               existing_type=sa.UUID(),
               comment='Document this transaction was extracted from (null for manual entries)',
               existing_comment='Document this transaction was extracted from (null for manual entries or dismissed documents)',
               existing_nullable=True)
    op.drop_column('transactions', 'source_document_name')
    # ### end Alembic commands ###
